apiVersion: apps/v1
kind: Deployment
metadata:
  name: js-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: js-api
  template:
    metadata:
      labels:
        app: js-api
    spec:
      containers:
        - name: js-api
          image: ghcr.io/lisa-vsqz/devsecops-ci-cd-js/js-api:latest
          ports:
            - containerPort: 3000
          env:
            - name: API_TOKEN
              value: "securetoken123"
